import razorpay
import logging
import uuid
from typing import Dict, Any
from app.core.config import settings

logger = logging.getLogger("razorpay_service")

class RazorpayService:
    def __init__(self):
        self.key_id = settings.RAZORPAY_KEY_ID
        self.key_secret = settings.RAZORPAY_KEY_SECRET
        self.is_demo = not self.key_id or not self.key_secret or self.key_id.startswith("rzp_test_demo")
        
        self.client = None
        if not self.is_demo:
            try:
                self.client = razorpay.Client(auth=(self.key_id, self.key_secret))
                logger.info(f"[RAZORPAY] Initialized Razorpay Test Mode Client with Key ID: {self.key_id[:8]}***")
            except Exception as e:
                logger.warning(f"[RAZORPAY] Failed to initialize Razorpay SDK client: {e}")
                self.is_demo = True

    def create_payment_link(
        self,
        amount: float,
        customer_name: str,
        customer_email: str,
        description: str,
        reference_id: str
    ) -> Dict[str, Any]:
        """
        Creates a Razorpay Payment Link using official Razorpay Payment Links API in TEST MODE,
        or interactive payment sandbox fallback if running in demo mode.
        Returns the exact short_url generated by Razorpay.
        """
        amount_paise = int(amount * 100)

        # 1. Official Razorpay API in Test Mode
        if not self.is_demo and self.client:
            try:
                link_data = {
                    "amount": amount_paise,
                    "currency": "INR",
                    "accept_partial": False,
                    "reference_id": reference_id,
                    "description": description,
                    "customer": {
                        "name": customer_name,
                        "email": customer_email,
                    },
                    "notify": {
                        "sms": False,
                        "email": True
                    },
                    "reminder_enable": True,
                    "callback_url": f"http://localhost:5173/cases?recovered_ref={reference_id}",
                    "callback_method": "get"
                }
                
                # Backend logging without secrets
                logger.info(f"[RAZORPAY REQ] Creating Payment Link for Ref: {reference_id}, Amount: INR {amount}")
                
                res = self.client.payment_link.create(link_data)
                
                short_url = res.get("short_url")
                link_id = res.get("id")
                status = res.get("status", "created")

                logger.info(f"[RAZORPAY RES] Success - ID: {link_id}, Short URL: {short_url}, Status: {status}")

                return {
                    "mode": "RAZORPAY_TEST_MODE",
                    "payment_link_id": link_id,
                    "short_url": short_url,
                    "payment_link_url": short_url,
                    "amount": amount,
                    "currency": res.get("currency", "INR"),
                    "status": status,
                    "created_at": res.get("created_at")
                }
            except Exception as e:
                logger.error(f"[RAZORPAY ERROR] Failed to create link via Razorpay API: {e}")

        # 2. Interactive Sandbox Fallback for Demo Mode (Valid working interactive URL)
        mock_id = f"plink_{uuid.uuid4().hex[:12]}"
        demo_url = f"http://localhost:8000/api/v1/razorpay/demo-payment-page/{mock_id}?amount={amount}&reference_id={reference_id}"
        
        logger.info(f"[RAZORPAY DEMO] Generated Interactive Sandbox Payment Link: {mock_id} -> {demo_url}")

        return {
            "mode": "DEMO_SANDBOX",
            "payment_link_id": mock_id,
            "short_url": demo_url,
            "payment_link_url": demo_url,
            "amount": amount,
            "currency": "INR",
            "status": "created",
            "message": "Generated interactive Razorpay Payment Link in Test Sandbox Mode."
        }

razorpay_service = RazorpayService()
